baseURL = 'https://palebluemarbles.com/'
languageCode = 'en-us'
title = "Pale Blue Marbles"

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

[caches]
  [caches.images]
    dir = ':cacheDir/images'